### PR TITLE
Added more optimization in signin and signup page with improving ui

### PR DESCRIPTION
**Pull request by AdityaPainuli**
Hey, 👋👋 there this is my first pr toward this repo I optimized sign in or sign-up page in which I made them in a component so that the page will not have to load every time user wants to switch between them only a certain component will load up also the supabase function for sign in and sign up is working fine as they are. I tried to make the UI good hope you like it.

image
image

### CODE REVIEW

**Comment by ykdojo** [comment]
A few things:

1. The screenshots look good.

2. Can you keep the same routes as before (/signin and /signup I believe) to avoid confusion?

3. Have you tested all the functionalities? Is there any extra step that's needed to set this up on the Supabase side other than what's already described in README?

**Comment by AdityaPainuli** [comment]
The sign in and sign up function is same as previous only what I did was make the UI more optimized

**Comment by ykdojo** [comment]
The routes have changed.

For example, here: https://defaang-git-fork-adityapainuli-main-ykdojo.vercel.app/

https://defaang-git-fork-adityapainuli-main-ykdojo.vercel.app/signup no longer works.

Also, did you test all the functionalities including the Google signup?

**Comment by AdityaPainuli** [comment]
No google signup didn't work right now It just a static button I will work on that one right now and for the routes I will also create them in two different page so that both of them will work as same

**Comment by ykdojo** [comment]
Hmm it says this was merged, but it's not showing up in the commit history - not sure why.

Anyway, I requested changes. If it was merged, which I'm not sure it was - can you revert it?

**Comment by AdityaPainuli** [comment]
let me try It is my first time trying these things out .

**Comment by AdityaPainuli** [comment]
hey can you help me I don't know why I can't push the code after I fixed the bug can you please help me with what should I do?
image

**Comment by ykdojo** [comment]
Can you just make a new branch and a new PR?

**Comment by AdityaPainuli** [comment]
Ok

**Pull request merged**
