### PR TITLE
chore: Submitted interview question

### PR DESCRIPTION
**Pull request by Sourz-101**
signed up at defaang.io and verified email
entered an interview question from my last interview with Atlassian happened almost 4 months ago

### CODE REVIEW

**Comment by ykdojo** [comment]
I believe this is the question you submitted:

> Given a list of [FileName, FileSize, [Collection]] - Collection is optional, i.e., a collection can have 1 or more files.
> 
> The same file can be a part of more than 1 collection. How would you design a system :
> to calculate the total size of files processed?
> to calculate Top K collections based on size?

It's the exact same question as [this one](https://leetcode.com/discuss/interview-question/1508471/code-design-file-processing-scenario).

What's going on?

**Review by ykdojo — CHANGES_REQUESTED** [review]
.

**Comment by Sourz-101** [comment]
please remove "spam" label as this could affect my hacktoberfest rating.
I think there is some misunderstanding 
I am willing to rectify the the issue
please consider

**Comment by ykdojo** [comment]
Are you saying you didn't submit the question that seemed to have been copied from Leetcode?

**Comment by Sourz-101** [comment]
Hello @ykdojo 
I am participating first time in Hacktoberfest/Open source
I thought the issue was that I just had to submit an "Interview question" irrespective of the source.
That was a genuine mistake.
Do not merge my PR, but please don't label it as spam.
It will affect in Hacktoberfest.
Please consider
Thank You

**Pull request closed without merging**
