### PR TITLE
dx: add Gitpod button to README

### LINKED ISSUE #84: [FEATURE] add GitPod button to README.md file
### Description

Setting up the project on a local machine is never fun. So I recently learned about GitPod, a pretty great service that allows us to work and contribute to projects directly from the browser.

Therefore, I want to include the GitPod button in this project.

### PR DESCRIPTION
**Pull request by RakeshSangem**
### 🛠️ Fixes Issue
closes #84

### CODE REVIEW

**Comment by iShibi** [comment]
Can you add `.gitpod.yml` to gitignore?

**Comment by RakeshSangem** [comment]
> Can you add `.gitpod.yml` to gitignore?

Hey @iShibi 👋

What is the reason for the issue here?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Review by rohitdasu — APPROVED** [review]
looks amazing.. we can run the app also from the online IDE. Nice add-on to the project 👍

**Comment by RakeshSangem** [comment]
> 



> looks amazing.. we can run the app also from the online IDE. Nice add-on to the project 👍

Everything can be done directly in the browser!

**Comment by rohitdasu** [comment]
> Can you add `.gitpod.yml` to gitignore?

i don't think gitpod will work fine without this

**Comment by iShibi** [comment]
> i don't think gitpod will work fine without this

Gitpod auto generates the`.gitpod.yml` file if it does not find one in the repo. If we want to support Gitpod more than just adding a button then @RakeshSangem should add it in this PR otherwise, the next person who uses Gitpod will have a diff right at launch. Not a good dx imo.

**Comment by RakeshSangem** [comment]
> > i don't think gitpod will work fine without this
> 
> Gitpod auto generates the`.gitpod.yml` file if it does not find one in the repo. If we want to support Gitpod more than just adding a button then @RakeshSangem should add it in this PR or add it to `.gitignore` otherwise, the next person who uses Gitpod will have a diff right at launch. Not a good dx imo.

Should I add this to .gitignore?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by iShibi** [comment]
yeah, as long as we don't have a need to customize the Gitpod config we should gitignore it otherwise the `.gitpod.yml` file created by Gitpod at launch will get added to the diff.

**Comment by ykdojo** [comment]
@RakeshSangem cool! You tested it to make sure it works right? Editing, hosting, env variables, etc.

**Comment by iShibi** [comment]
@RakeshSangem You have a prettier error, run `npm run format:fix` to resolve it. Also, try to use conventional git commit messages.

Make sure you have all the devDeps installed and the husky git hooks are working when you commit, those will take care of all the above issues.

**Comment by RakeshSangem** [comment]
> 


> @RakeshSangem You have a prettier error, run `npm run format:fix` to resolve it. Also, try to use conventional git commit messages.
> 
> Make sure you have all the devDeps installed and the husky git hooks are working when you commit, those will take care of all the above issues.

I'll test in my branch first!

**Comment by benny123tw** [comment]
Maybe we could add some description about Gitpod like [Remix#prerequisites](https://remix.run/docs/en/v1/tutorials/blog#prerequisites):
### Prerequisites
Click this button to create a [Gitpod](https://gitpod.io/) workspace with the project set up and ready to run in VS Code or JetBrains either directly in the browser or on the desktop.  

[Open in Gitpod](https://gitpod.io/#https://github.com/ykdojo/defaang)

What do you guys think?

**Comment by ykdojo** [comment]
I don't think it's a pre-requisite?

Also since @RakeshSangem is busy, I'm going to close this.

**Pull request closed without merging**
