### PR TITLE
dx: add commit-msg git hook to run commitlint

### PR DESCRIPTION
**Pull request by iShibi**
### 👨‍💻 Changes proposed

Added `commitlint` to lint commit messages. It is executed by the newly added `commit-msg` husky git hook that runs on every `git commit` cmd. This change will force contributors to follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

commitlint

### CODE REVIEW

**Comment by ykdojo** [comment]
@rohitdasu do you want to try reviewing this?

**Comment by ykdojo** [comment]
or @subhoghoshX?

**Comment by rohitdasu** [comment]
I can pick this @ykdojo

**Review by rohitdasu — APPROVED** [review]
great DX @iShibi

**Pull request merged**
