### PR TITLE
feat: Added greetings message

### PR DESCRIPTION
**Pull request by bishal7679**
### ➕ Changes Introduced

Added greetings message!

### CODE REVIEW

**Comment by subhoghoshX** [comment]
There seems to be an error. Could you look into that?

**Review by adilwahla — COMMENTED** [review]
can you explain reason why is it necessary?

**Comment by bishal7679** [comment]
> can you explain reason why is it necessary?

Don't you like to greet the first time contributor?
then I will close this PR!

**Comment by adilwahla** [comment]
> There seems to be an error. Could you look into that?

there  are few checks needed to pass may be you need to improve title of commit

**Pull request closed without merging**
