### PR TITLE
dx: improve project template

### PR DESCRIPTION
**Pull request by iShibi**
### 👨‍💻 Changes proposed

1. ESLint
   - Checks the code for errors and fixes it on save and during commit.
2. Prettier
   - Formats code on save and during commit to keep a consistent style in the codebase.
3. Test Workflow for PRs
   - Runs eslint, prettier, and tsc on PRs.
4. Husky
   - Allows to run git hooks
5. `_document.tsx` page to add default meta tags for the website
6. lint-staged
   - Runs ESlint and Prettier before committing
7. Add `.vscode` folder for editor configuration and plugin suggestion
8. Update dependencies

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by rohitdasu** [comment]
@iShibi nice PR 🎉 Looks good to me!  
But i've some request, please add some information about vscode setup configuration in the README.md file so it will be helpful. Thanks

**Review by rohitdasu — APPROVED** [review]
@iShibi nice PR 🎉 Looks good to me!
But i've some request, please add some information about vscode setup configuration in the README.md file so it will be helpful. Thanks

**Comment by ykdojo** [comment]
Thank you. It looks like there's a lot of stuff in here.

My questions:

> Test Workflow for PRs
> Runs eslint, prettier, and tsc on PRs.
What's tsc?

> Husky
> Allows to run git hooks
What is this needed for?

> _document.tsx page to add default meta tags for the website
What's this for?

Also @rohitdasu, thank you for reviewing it - did you want to review it after the new changes?

**Comment by rohitdasu** [comment]
> Thank you. It looks like there's a lot of stuff in here.
> 
> My questions:
> 
> > Test Workflow for PRs
> > Runs eslint, prettier, and tsc on PRs.
> 
> What's tsc?
> 
> > Husky
> > Allows to run git hooks
> 
> What is this needed for?
> 
> > _document.tsx page to add default meta tags for the website
> 
> What's this for?
> 
> Also @rohitdasu, thank you for reviewing it - did you want to review it after the new changes?

hi @ykdojo i have reviewed the new changes, LGTM but you can check from your side it would be better.

**Comment by rohitdasu** [comment]
Husky is nowadays very popular tool. It can prevent any unwanted linting errors to commit.

**Comment by ykdojo** [comment]
Also another thing:

I don't think we should call this a "chore".

To me, it sounds like something boring to do, but isn't it an important thing to do?

I'd call it something like *dx* as in developer experience improvement.

**Comment by iShibi** [comment]
@ykdojo

> What's tsc?

TypeScript Compiler. The test workflow runs eslint, prettier, and `npm run build` (this is where tsc runs) to make sure the PR is ready to merge.

> Husky, What is this needed for?

Husky executes `lint-staged` when a user performs `git commit` to auto-fix lint and formatting errors.

> `_document.tsx`, What's this for?

In next.js we can use the `<Head>` component in a page to define meta tags specific to that page but some meta tags are common among all the pages. The `_document.tsx` page allows to define those tags in one place. It also lets you to add classes to the `body` element.

> I don't think we should call this a "chore".

`chore` refers to the type of changes not the importance. Out of all the recommended types from [conventionalcommits.org](https://www.conventionalcommits.org/en/v1.0.0/#summary), chore seems to be the best match for this PR. I would have used `dx` if you want but it's not defined in the convention.

⚠️ Merging #42 caused some conflicts in this PR, working on fixing it.

**Comment by ykdojo** [comment]
> chore refers to the type of changes not the importance. Out of all the recommended types from conventionalcommits.org, chore seems to be the best match for this PR. I would have used dx if you want but it's not defined in the convention.

Yes I think dx would be good for this one. It is defined in *our* convention haha

And thank you so much for clarifying everything!

**Comment by ykdojo** [comment]
changed chore -> dx, and I was going to close it, but it looks like we have merge conflicts.

mind taking a look?

**Comment by iShibi** [comment]
@ykdojo All conflicts were taken care of, this is ready to be merged.

**Pull request merged**
