### PR TITLE
feat: made the submission box (front-end only for now)

### LINKED ISSUE #59: [FEATURE] <A question submission box> (frontend)
Quoting myself from #10:

> The first step is the signup flow as I mentioned at https://github.com/ykdojo/defaang/issues/14, and then after that, maybe a submission box? We can store them privately for now (probably in Supabase or Firebase), and once we have a few, we can make a view for showing those questions.

This should be possible to implement as we have #33 and #34 implemented already.

### PR DESCRIPTION
**Pull request by ykdojo**
- Made the submission box - frontend only for now. Available at /submit
- The backend will be set up later with #108

### screenshot:

image

closes #59 and #127

### CODE REVIEW

**Comment by RakeshSangem** [comment]
In order to filter the data/questions in the future, why don't we use tags for questions(arrays, binary trees etc.) ?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by ykdojo** [comment]
I'd rather keep it simple and not implement tags for now. Maybe later

**Comment by subhoghoshX** [comment]
Looks good, thank you. I'm not sure about importing all those static fonts. But it's nothing critical I guess, we can optimize later.

I think making the form fields full width and applying some padding on the parent container, might make it look better. Something like below (Open to discuss though). And also a little bit of rounded corner hehe.

image

**Comment by subhoghoshX** [comment]
Also if I remember correctly, we were supposed to have a separate question and question description field. Looks like you merged it into one.

And also a question category and job title field.

**Comment by RakeshSangem** [comment]
> Also if I remember correctly, we were supposed to have a separate question and question description field. Looks like you merged it into one.
> 
> And also a question category and job title field.

yes, title and description should be there!

**Comment by ykdojo** [comment]
Added position and question fields:

image

For styling, I think we can make it a separate issue/PR? @subhoghoshX

**Comment by subhoghoshX** [comment]
Sure that'd be better. I think we can merge it then.

**Pull request merged**
