### PR TITLE
dx: add the ability to debug Next.js backend code with Chrome Dev Tools

### PR DESCRIPTION
**Pull request by ykdojo**
more info: https://nextjs.org/docs/advanced-features/debugging

### CODE REVIEW

**Comment by iShibi** [comment]
Let's add `cross-env` as a devDep to make sure this works on Windows too. See: https://nextjs.org/docs/advanced-features/debugging#debugging-on-windows

**Comment by iShibi** [comment]
@ykdojo we can merge this if you can add the above-requested changes.

**Comment by ykdojo** [comment]
@iShibi I'll come back to this if/when I start working on #108

**Comment by ykdojo** [comment]
@iShibi should be fixed now

**Review by iShibi — APPROVED** [review]

**Pull request merged**
