### PR TITLE
dx: Added a new issue template for DX improvements / refactoring

### PR DESCRIPTION
**Pull request by rohitdasu**
### 👨‍💻 Changes proposed

added a new template for DX issue

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Jonyango — APPROVED** [review]
I reviewed this, and it looks good.

**Comment by AdityaPainuli** [comment]
I think we also should mention all the tech stack which are ok to use in the project it will help new contributors to know what they can use on the package and what not  . what you guys say ?

**Comment by rohitdasu** [comment]
> I think we also should mention all the tech stack which are ok to use in the project it will help new contributors to know what they can use on the package and what not  . what you guys say ?

Cool, create an issue for that and discuss. I don't think this PR is right place to discuss that 😅

**Comment by iShibi** [comment]
Edit the PR title to follow the conventional commit message other than that everything looks good.

**Comment by rohitdasu** [comment]
> Edit the PR title to follow the conventional commit message other than that everything looks good.

so which one it should be from conventional commit?

**Comment by iShibi** [comment]
using `dx` makes the best sense here.

**Pull request merged**
