### PR TITLE
dx: add global state management

### LINKED ISSUE #169: [FEATURE] Add global state management
### Description

I'll start the work on adding global state management today. This issue has been created to track its implementation.

I have been using https://redux-toolkit.js.org/ for a long time now and it has been great to work with. I tried other libraries but none of them is as good as it is. If you have any input to provide, please feel free to do so here or on the related PR (yet to open)

### PR DESCRIPTION
**Pull request by iShibi**
Closes #169
- #169

### CODE REVIEW

**Comment by ykdojo** [comment]
I was doing some research on this, and I'm wondering if we need Redux for this app.

What do you think about simply using [React Context](https://stackoverflow.com/questions/69675357/react-what-is-the-proper-way-to-do-global-state) for it, instead?

**Comment by iShibi** [comment]
> What do you think about simply using [React Context](https://stackoverflow.com/questions/69675357/react-what-is-the-proper-way-to-do-global-state) for it, instead?

Redux Toolkit provides a better and easier developer experience. Updating the shared state is also easy and then there is the Redux devtool for debugging purposes. The website is going to be large and dynamic in nature. Redux Toolkit is best suited for our use case.

**Comment by ykdojo** [comment]
I think Redux is just way too complex for what we have right now. All we need is basically a way to keep track of the user session and the user.

[More context](https://twitter.com/reactive_dude/status/1565366045879275522).

We've had a discussion about it on [#share-resources](https://discord.com/channels/1007344194622324807/1012873382389350470) on Discord, too.

**Comment by CerealPlayer** [comment]
I agree with YK. Redux is kind of an old giant. For this apps purpose React Context could definitely work

**Comment by ykdojo** [comment]
@iShibi are you still working on this? If not, I'll close it and go back to #167.

**Pull request closed without merging**
