### PR TITLE
dx: plausible analytics added

### LINKED ISSUE #93: [DX] add Hotjar for getting user feedback and issue tracking
### Description

We are not live yet, but it's a good idea to add Hotjar script that will help analyse our apps performance and get feedbacks when we get to Beta or similar kind of stage. 

Would love to know your suggestion.

### PR DESCRIPTION
**Pull request by rohitdasu**
### 🛠️ Fixes Issue #93 

 Closes #93 

### 👨‍💻 Changes proposed

added flausible(https://plausible.io) analytics

### CODE REVIEW

**Comment by ykdojo** [comment]
What are the steps required to set this up?

**Comment by rohitdasu** [comment]
steps for setting up flausible? @ykdojo

**Comment by ykdojo** [comment]
yes

**Comment by rohitdasu** [comment]
done @ykdojo

**Comment by ykdojo** [comment]
@rohitdasu thank you.

It looks good, but I feel like it's too early to merge right now.

It adds an extra step to setting up the environment, and we don't have any traffic to the site yet.

I think we can merge it once we have more significant traffic coming in?

**Comment by rohitdasu** [comment]
> @rohitdasu thank you.
> 
> It looks good, but I feel like it's too early to merge right now.
> 
> It adds an extra step to setting up the environment, and we don't have any traffic to the site yet.
> 
> I think we can merge it once we have more significant traffic coming in?

sure, should I move this PR to draft to make sure we don't merge it accidentally ?

**Comment by ykdojo** [comment]
yes making it a draft PR sounds good!

**Review by subhoghoshX — APPROVED** [review]

**Review by mark-omarov — APPROVED** [review]

**Pull request closed without merging**
