### PR TITLE
feat: (added authentication with social)

### PR DESCRIPTION
**Pull request by AdityaPainuli**
# Added Social Account Authentication with Github and Google.

## Here are some screenshots of the Website: -
image
image

### CODE REVIEW

**Review by rohitdasu — CHANGES_REQUESTED** [review]
please add docs in readme.md file for google and github auth setup in supabase

**Comment by iShibi** [comment]
@AdityaPainuli Your lockfile is out of sync again. Delete `package-lock.json` and run `npm i` to sync it. Also, make sure not to work directly in the `main` branch from now on. Once this PR is merged run `git pull upstream main` and checkout a new branch for any future PR.

**Comment by ykdojo** [comment]
I think we should remove "Sign In using other social networks" and "Sign up using other social networks" to keep the UI simple.

**Comment by AdityaPainuli** [comment]
> I think we should remove "Sign In using other social networks" and "Sign up using other social networks" to keep the UI simple.

If it's okay with all of you then we should remove it .

**Comment by ykdojo** [comment]
> please add docs in readme.md file for google and github auth setup in supabase
Did you address this yet?

**Comment by AdityaPainuli** [comment]
I am waiting to get approval from all the members about social authentication if you all agree on this then I will start adding docs.

**Comment by ykdojo** [comment]
I think the general idea is good, but it'll be good to have documentation for it

**Comment by AdityaPainuli** [comment]
Alright then I will work on the documentation

**Comment by AdityaPainuli** [comment]
Hey as I am writing the docs for authentication through a social platform I think it will be easy to attach a video to it as it is a bit of work on the cloud console and GitHub developer page. Can I add the video to the readme? Because without video the readme will become very long which I don't think is good

**Comment by ykdojo** [comment]
Yes the video would be great. Thank you!

**Comment by AdityaPainuli** [comment]
Here is the video for both authentication . As Github has a limit of 10MB of media I tried to keep the quality lower for both of the videos.
https://user-images.githubusercontent.com/66621672/185778299-9ef3b994-2889-485b-bd39-b2ea20fa305f.mp4

https://user-images.githubusercontent.com/66621672/185778669-df9a3510-58d2-4844-b8b0-7a99103dd813.mp4

**Comment by ykdojo** [comment]
Thank you! Did you add it in README?

**Comment by AdityaPainuli** [comment]
Added the videos to README

**Comment by ykdojo** [comment]
Thank you. This looks good, but I never realized it would take so much work to set up Google/GitHub signups.

Given that, I think it makes sense to hold off on merging this PR so we can merge it later when we have a properly working product.

So could you please make it a draft PR for now?

**Pull request closed without merging**
