### PR TITLE
dx: remove commitlint package and add PR title checker to workflow

### LINKED ISSUE #125: [DX] <Remove the commit message restriction on Husky>
### Description

I think we should remove the commit message restriction on Husky.

I get the value of conventional commit messages, but most commits shouldn't show up anyway as long as we squash and merge PRs.

So, as long as the commits on the main branch have the proper format, individual commit messages shouldn't matter so much.

### PR DESCRIPTION
**Pull request by benny123tw**
### 🛠️ Fixes Issue

Closes #125 

### 👨‍💻 Changes proposed

* Remove devDependencies `@commitlint/cli` and `@commitlint/config-angular`
* Remove `.commitlintrc.json`
* Remove git hook `commit-msg`
* Add PR title checker to workflow

### 📄 Note to reviewers

I'm not good at RegExr. I would appreciate it if someone could improve the syntax.

It will match all the types in CONTRIBUTING.md and include the scope and `!`.

e.g.
style(global.css)!: message -> pass  

If the PR title doesn't match the RegExr, it will add the label `title-needs-formatting` (We can customize the label's name and color).

### 📷 Screenshots

none

### CODE REVIEW

**Comment by ykdojo** [comment]
Thank you! How did you test it?

**Review by ykdojo — APPROVED** [review]

**Comment by benny123tw** [comment]
> Thank you! How did you test it?

I tested it in my [repo](https://github.com/benny123tw/github-action-test/pull/2) by changing the PR title name to try if the RegExr is correct.

**Comment by iShibi** [comment]
I tested the regex and it isn't matching a valid conventional commit message. After some quick google searches, I found the following regex:
```
^(feat|fix|docs|style|refactor|test|dx|chore){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)
```
Source: https://gist.github.com/marcojahn/482410b728c31b221b70ea6d2c433f0c

**Comment by iShibi** [comment]
Hey @benny123tw, I tested the new regex and this one also doesn't match. It's fine, you can add the above regex and we will merge.

**Comment by benny123tw** [comment]
> Hey @benny123tw, I tested the new regex and this one also doesn't match. It's fine, you can add the above regex and we will merge.

I did copy the above regex, but added double backslashes for JSON.

**Review by iShibi — APPROVED** [review]

**Pull request merged**
