### PR TITLE
solved redirecting back from submission page to Homepage

### LINKED ISSUE #271: [BUG] Figure out a better way to redirect from the question submission page
### Description

When you try to go to the question submission page before logging in, you're redirected to the signup page.

This behavior is good, but with the current redirect method, the back button doesn't work.

Is there a better way to redirect to avoid this issue?

### PR DESCRIPTION
**Pull request by sanyamjain04**
### 🛠️ Fixes Issue
Closes #271 

### ➕ Changes Introduced

I have changed the Router method in the signup file from `push` to `replace`.

### CODE REVIEW

**Comment by Olyno** [comment]
Hi 👋🏻 Your fix works better than my PR indeed, but you did the change at the wrongplace 😄

**Comment by subhoghoshX** [comment]
Hey, thanks for you working on it, but I don't think this is what YK addressed in the issue. Just to give you a hint, I don't think it can be done on the client side. You probably want to SSR the page on every request.

**Comment by sanyamjain04** [comment]
Oh ya sorry I actually did a silly mistake

**Comment by sanyamjain04** [comment]
Now it's solved @ykdojo

**Comment by Olyno** [comment]
I personally would prefer making the authentication part on the server side. By doing that, we don't see the redirection on the client side, it just loads the page correctly. Also, localStorage lacks of security too, it's one more reason to use on the server side.

That being said, the PR does meet the need, so I have nothing against it.

**Comment by Olyno** [comment]
I'm confused, why closing the pull request? @sanyamjain04

**Comment by sanyamjain04** [comment]
> I'm confused, why closing the pull request? @sanyamjain04

you just said that the PR doesn't meet the need.

**Comment by sanyamjain04** [comment]
oh sorry, I read it wrong. I think I need some sleep 🥲🥲😂

**Comment by Olyno** [comment]
It's okay ahah, sorry for making it confusing 😅

**Pull request merged**
