### PR TITLE
UX wireframe for the Website

### PR DESCRIPTION
**Pull request by Swaraj-Singh-30**
There are two files in the PR. If facing any problem opening file, go the one where a link is mentioned. ID ready to go with the design I will create UI using figma. If there are some changes required you can let me know.

https://excalidraw.com/#json=R6Dr_C1S9JMKNl1lKVdkZ,5Cpg-gVKd0mzRfLXUfz9aA

### CODE REVIEW

**Comment by Dun-sin** [comment]
You could do this by creating an issue instead of creating a pull request

**Comment by Swaraj-Singh-30** [comment]
Ohh yeah 👍

I read "Feature request as issue" As "pull request" In redme file

My bad

**Comment by Swaraj-Singh-30** [comment]
Made a blunder 

Thanks Dunsin for figuring it out 👍🏻

**Review by ykdojo — COMMENTED** [review]
woah thank you so much!!!

feel free to reopen this as a PR :)

**Comment by Swaraj-Singh-30** [comment]
Opened 😄😊

**Comment by ykdojo** [comment]
ty! reviewing it asap.

mind putting them in a single folder, though?

**Comment by ykdojo** [comment]
Questions:
1. What's the alumni section for?
2. Any chance we can have something simpler to get started with so it's easier for everyone to implement it?

Thank you so much again!

I'm actually going to re-close this again and bring the discussion to the issue.

Once we have a clear picture of what the first iteration should look like, then I'll be happy to merge it!

**Comment by Swaraj-Singh-30** [comment]
Alumni section can be for the people who found it useful and gave us a feedback so we can attach that feedback as a proof the we are credible enough.

**Comment by Swaraj-Singh-30** [comment]
I can surely make a simpler version

If you can elaborate a little about what should the simpler version be about, like specifically hero - banner or main content page or question and solution page, which one? It will make my work a bit easier 😊

**Comment by RakeshSangem** [comment]
> Alumni section can be for the people who found it useful and gave us a feedback so we can attach that feedback as a proof the we are credible enough.

Testimonals?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by Swaraj-Singh-30** [comment]
Yeah.

Summary is like what is Dfanng, it's objective and some more stuffs

**Comment by ykdojo** [comment]
@Swaraj-Singh-30 I answered earlier your question here: https://github.com/ykdojo/defaang/issues/10

**Pull request closed without merging**
