### PR TITLE
feat: added boilerplate code for next.js + tailwind

### LINKED ISSUE #27: Start with some boilerplate code for Next.js + Tailwind
This is probably a good place to start since we don't have any code in this repo yet.

We can probably use this: https://github.com/vercel/next.js/tree/4d4f3093019179b1928ec07c16f38882241c0375/examples/with-tailwindcss

### PR DESCRIPTION
**Pull request by rohitdasu**
### 🛠️ Fixes Issue

Closes #27

### 👨‍💻 Changes proposed

#Added boilerplate code for the next.js + tailwindCSS

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

It's a boiler plate code for the next.js + tailwindcss
link - https://github.com/vercel/next.js/tree/4d4f3093019179b1928ec07c16f38882241c0375/examples/with-tailwindcss

### 📷 Screenshots

Screenshot 2022-08-12 at 11 37 50 PM

### CODE REVIEW

**Comment by ykdojo** [comment]
Thank you!

Any chance you could add documentation on setting it up / running it?

**Comment by rohitdasu** [comment]
> Thank you!
> 
> Any chance you could add documentation on setting it up / running it?

yeah nice idea, do you want me to add it into existing readme.md file?

**Comment by ykdojo** [comment]
> yeah nice idea, do you want me to add it into existing readme.md file?

yes I think that's the right approach here

**Comment by rohitdasu** [comment]
hi @ykdojo i've updated the readme.md file. please have a look at it. Thanks

**Comment by ykdojo** [comment]
Thank you! Looks good to me

**Pull request merged**
